apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-xzii
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-xzii
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-xzii
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-xzii
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-xzii
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zsyc-tenant/rhtap-demo-app/hacbs-test-project-xzii@sha256:dd4152886b6022acebb4f8f38281b65f6abd67d12e1513a868bb57f5d954fddd
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
