apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-xzii
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zsyc-tenant/rhtap-demo-app/hacbs-test-project-xzii@sha256:702cae16996458f8c3b77c7080aae171bd9e2d830cc3d14d0fbea8807b5e8db3
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
